### ISSUE TITLE
Set up API for bro site

### ISSUE THREAD

**Issue by bro-n-bro-0** [bro-n-bro/bro_site_api#3]
All instructions in the README
you can choose host and port at `config.py` variables

Serve it on our general `Hasura` server 

Set up CORS if it needed
the API should be available at `/bro_data` endpoint

**Comment by altbro** [comment]
@Braiteck please check if cors ok 
https://rpc.bronbro.io/bro_data/

**Comment by prevetal** [comment]
@altbro 
CORS Error: The request has been blocked because of the CORS policy

**Comment by altbro** [comment]
done
