### ISSUE TITLE
Incorrect data on landing page

### ISSUE THREAD

**Issue by bro-n-bro-2** [bro-n-bro/bro_site_api#6]
![image](https://github.com/bro-n-bro/bro_site_api/assets/89855562/4375728a-2d5a-4f35-81f1-bf42083597a2)
![image](https://github.com/bro-n-bro/bro_site_api/assets/89855562/eac667dc-3a5b-4369-ad2e-d96b519be61c)

**Comment by broVeider** [comment]
Requests to emoney were causing errors. Deleted from config.
